//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeDetail
    {
        public int Id { get; set; }
        public string MasterCode { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Code { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public bool IsInactive { get; set; }
    }
}
