//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correspondence
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string CustomId { get; set; }
        public string ForeignId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> ReportingId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> AssignedId { get; set; }
        public Nullable<int> ReviewedId { get; set; }
        public Nullable<bool> isSelf { get; set; }
        public Nullable<System.DateTime> ReceivedDt { get; set; }
        public Nullable<System.DateTime> AssignedDt { get; set; }
        public Nullable<System.DateTime> DueDt { get; set; }
        public Nullable<System.DateTime> ReviewDt { get; set; }
        public Nullable<bool> isWB { get; set; }
        public Nullable<bool> isLetterSent { get; set; }
        public Nullable<System.DateTime> LetterDt { get; set; }
        public string Explaination { get; set; }
        public string RecordLocation { get; set; }
        public Nullable<int> DispositionId { get; set; }
        public Nullable<System.DateTime> DecisionDt { get; set; }
        public Nullable<System.DateTime> ClosedDt { get; set; }
        public string IdentifyCosts { get; set; }
        public Nullable<System.DateTime> IdentifyCostsDt { get; set; }
        public string AvoidanceCosts { get; set; }
        public Nullable<System.DateTime> AvoidanceCostsDt { get; set; }
        public string QuestionCosts { get; set; }
        public Nullable<System.DateTime> QuestionCostsDt { get; set; }
        public string RecoveredCosts { get; set; }
        public Nullable<System.DateTime> RecoveredCostsDt { get; set; }
        public bool IsInactive { get; set; }
        public Nullable<int> EntBy { get; set; }
        public Nullable<System.DateTime> EntDt { get; set; }
        public Nullable<int> ChgBy { get; set; }
        public Nullable<System.DateTime> ChgDt { get; set; }
    }
}
