//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListColumn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListColumn()
        {
            this.ListColumnOptions = new HashSet<ListColumnOption>();
            this.ListColumnValues = new HashSet<ListColumnValue>();
        }
    
        public int Id { get; set; }
        public int ListId { get; set; }
        public string ColumnTitle { get; set; }
        public string ColumnDesc { get; set; }
        public string ColumnType { get; set; }
        public Nullable<int> ColumnOrder { get; set; }
        public string LabelCols { get; set; }
        public string ValueCols { get; set; }
        public Nullable<int> ValueLength { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<int> TextAreaCols { get; set; }
        public Nullable<int> TextAreaRows { get; set; }
        public bool Active { get; set; }
    
        public virtual List List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListColumnOption> ListColumnOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListColumnValue> ListColumnValues { get; set; }
    }
}
