//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListValue
    {
        public int Id { get; set; }
        public int ObjectId { get; set; }
        public string ObjectCode { get; set; }
        public int ListId { get; set; }
        public string JSONText { get; set; }
    
        public virtual List List { get; set; }
    }
}
