//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int ClientId { get; set; }
        public string InsCompany { get; set; }
        public string InsId { get; set; }
        public Nullable<System.DateTime> DtEnt { get; set; }
    }
}
