//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenu
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string StateName { get; set; }
        public string StateJSON { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
